sudo: false
language: go
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get github.com/go-critic/go-critic/...
go:
  - "1.11"
before_script:
  - go vet ./...
  - golint -set_exit_status ./...
  - gocritic check-project --enable=all -withExperimental -withOpinionated .
  - ./scripts/imports
  - ./scripts/format
script:
  - ./scripts/test
after_success:
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
