sudo: false
language: go
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
go:
  - "1.10"
before_script:
  - go vet ./...
  - golint -set_exit_status ./...
  - ./scripts/imports
  - ./scripts/format
script:
  - ./scripts/test
after_success:
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
